spring.application.name=user
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/auth_ms
spring.datasource.username=usr
spring.datasource.password=pwd
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver